### ISSUE TITLE
QUESTION: Is it possible to get JSON logs in logentries?

### ISSUE THREAD

**Issue by jlchereau** [logentries/le_js#40] opened 2015-04-23 16:37 UTC
This is what I get with **le_js**:
![image](https://cloud.githubusercontent.com/assets/2556751/7302118/0f6f0658-e9df-11e4-9e9b-d17db23eb8c7.png)

...and this is what I get with **le_node**:
![image](https://cloud.githubusercontent.com/assets/2556751/7302157/49365076-e9df-11e4-9f78-ebc2f5a1cd51.png)

Is there any way to format logs brought from le_js as JSON like le_node?

**Comment by chrismatheson** [comment] 2015-04-24 09:03
@jlchereau yeah i have the same problem, would love to see JSON formatted logs for client side :+1:

**Comment by atlesp** [comment] 2015-05-08 08:33
we also wish the same. It is strange that they do not support it, for the talk about key values in the documentation for it https://github.com/logentries/le_js/wiki/API#log

**Comment by m0wfo** [comment] 2015-05-27 09:39
A bit of context: prior to our ability to process JSON on the fly within the app, we came up with this serialization format for accessing, e.g. nested key-value pairs. You're right in thinking that this is no longer necessary. Not only that, but having to do deep inspection of incoming payloads restricts the throughput for this portion of our service.

Since this is not a *totally* trivial change, I'd say the best thing to do is send a [feature request](https://trello.com/b/ICckMDvF/logentries-feature-request) asking for le.js to send verbatim JSON payloads (I'll upvote it!) or contact support.

Sending the JSON straight through raises another open question- would we want to keep sending metadata like log levels, browser capabilities, trace codes, e.t.c. or have it behave just like the node.js client? If that's the case, does it make sense to have two JS clients? Just playing devils' advocate here :)

**Comment by bathos** [comment] 2015-06-03 18:39
@m0wfo: I’d say it still makes sense to maintain them as unique libraries.

This library submits over HTTP and aims for backwards compatibility with medieval browsers while remaining as small as possible. The node library is larger -- much larger when factoring in dependencies, and much, much larger when factoring in the shims that would be required to use it in the browser. It might be appropriate for certain client-side use in cases of web applications that already pack with Browserify & are loading shims, but otherwise it'd be overkill.

Expanding le_js’ functionality to support JSON logs seems (..."seems") reasonably simple to me. A few things from the node lib can be carried over, but not verbatim -- for one, we want to keep this tiny, and two, I was able to make environmental assumptions in Node that are not necessarily true in the browser. For example, when performing error serialization in Node we know we’re dealing with the V8 implementation, but iirc FF & IE have differences there.

I could take a look into this if you like.

**Comment by jlchereau** [comment] 2015-06-03 20:00
+1

**Comment by atlesp** [comment] 2015-06-03 20:04
+1

**Comment by StephenHynes7** [comment] 2015-06-04 09:26
@bathos The issue isn't on the client side of things and on the server side of le_js where this meta data (IP and such) get added in which breaks up the format. I agree that the ability to toggle whether your log gets sent as pure JSON would be advantageous.

**Comment by m0wfo** [comment] 2015-06-04 13:18
Ok guys- there's a suggestion on the trello board [here](https://trello.com/c/pm4SZc2K/97-configure-le-js-to-send-json-to-logentries)- if you still feel strongly about it, go and upvote it :)

**Comment by bathos** [comment] 2015-06-04 13:52
@StephenHynes7 Ah, of course -- I didn't realize the js endpoint was supplying data. I was just thinking in terms of the data.logentries endpoint. If a user doesn't need that, though, is it currently possible to configure le_js to use the data endpoint and allow arbitrary log data?

**Comment by StephenHynes7** [comment] 2015-06-04 13:56
data.logentries.com (atm) only accepts TDP/UDP connections and not POST request so the le_js backend server is required.

**Comment by bathos** [comment] 2015-06-04 14:07
Interesting. Yeah, we’d need to use Forge to get TCP in the client and that’s just too big for this. Do you know why this user was able to send an HTTP req to the data endpoint with "/logs/{TOKEN}" successfully (or somewhat successfully)?:

http://forum.logentries.com/t/how-to-submit-json-log-entries-without-a-library

**Comment by StephenHynes7** [comment] 2015-06-04 14:11
That example is still sending over TCP and not HTTP hence why its working http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/Socket.html.

**Comment by bathos** [comment] 2015-06-04 14:56
Yup, the code posted there was the solution he or she arrived at. But I was referring to the first attempt that was described in the initial question:

> Make a POST HTTP request to data.logentries.com/logs/MY_TOKEN?asdf -- This works, but I seem to be only able to send short strings (the asdf) part, and its not pretty formatted, and does not like URL encoding.

From the sound of it, it *shouldn't* have worked at all. On one hand, an HTTP req is just a layer over TCP, but on the other, the format of an HTTP request seems to preclude anything getting through. The first line would have been `POST /logs/{token}?asdf HTTP 1.1\n` or something similar, and that seemingly shouldn't have been recognizable, so I'm wondering what might account for "asdf" getting through (assuming the account is accurate).

This isn't actually important, so don't feel any obligation to explain -- it's just excessive curiosity on my part now. :)

**Comment by chrismatheson** [comment] 2015-06-04 15:18
@bathos i had the same thoughts as you (http is just sitting onto of TCP) and tried a couple of experiments.

to send JSON logs into le via the data endpoint i *think* you could craft a http message, squirt it at data.le.com and as long and the body is a new line delim strings of JSON prepended with your token things should all work.

The only problem is that data.le.com will keep the connection open, so you would need to figure out a way of knowing absolutely that the request had been collected successfully and then close the connection from the client side.

it might be worth an "experimental" option that does this, and just monitor how useful it is ?

**Comment by bathos** [comment] 2015-06-04 16:18
@chrismatheson I just cURLed that in various permutations and nothing came through. I don’t seem to be able to replicate what the forum user described, either.

**Comment by chrismatheson** [comment] 2015-06-04 16:19
Hmmmm maybe it has changed. I'll give it a whirl next time I am in front of a machine :)

**Comment by jlchereau** [comment] 2015-08-19 10:06
Any progress with this?

**Comment by m0wfo** [comment] 2015-12-09 18:09
@gearoidof fixed with #60

**Closed by m0wfo** 2015-12-09 18:09 UTC
Labels: enhancement
